-- Run this if the database does not exist yet
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'SJ_PC_STORE')
BEGIN
    CREATE DATABASE SJ_PC_STORE;
END
GO

USE SJ_PC_STORE; 
GO

-- ==========================================
-- 1. SAFE DROP (Reverse Dependency Order)
-- ==========================================
IF OBJECT_ID('TRANSACTION_ITEM', 'U') IS NOT NULL DROP TABLE TRANSACTION_ITEM;
IF OBJECT_ID('[TRANSACTION]', 'U') IS NOT NULL DROP TABLE [TRANSACTION];
IF OBJECT_ID('STOCK_INSTANCE', 'U') IS NOT NULL DROP TABLE STOCK_INSTANCE;
IF OBJECT_ID('ITEM_MASTER', 'U') IS NOT NULL DROP TABLE ITEM_MASTER;
IF OBJECT_ID('PROCUREMENT', 'U') IS NOT NULL DROP TABLE PROCUREMENT;
IF OBJECT_ID('CATEGORY_LIST', 'U') IS NOT NULL DROP TABLE CATEGORY_LIST;
IF OBJECT_ID('SUPPLIER', 'U') IS NOT NULL DROP TABLE SUPPLIER;
IF OBJECT_ID('[USER]', 'U') IS NOT NULL DROP TABLE [USER];
GO

-- ==========================================
-- 2. CREATE TABLES
-- ==========================================
CREATE TABLE [USER] (
    UserID VARCHAR(20) PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    ContactNumber VARCHAR(15),
    Username VARCHAR(50) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    Role VARCHAR(20) NOT NULL, -- e.g., Admin, Cashier
    Passkey VARCHAR(6) NOT NULL,
    Status VARCHAR(20) DEFAULT 'Active'
);

CREATE TABLE SUPPLIER (
    SupplierID VARCHAR(20) PRIMARY KEY,
    CompanyName VARCHAR(100) NOT NULL,
    ContactNumber VARCHAR(15),
    Address VARCHAR(255)
);

CREATE TABLE CATEGORY_LIST (
    CategoryName VARCHAR(50) PRIMARY KEY
);

-- Insert default categories based on our HTML preview
INSERT INTO CATEGORY_LIST (CategoryName) VALUES ('Motherboard'), ('Processor'), ('RAM'), ('Graphics Card'), ('Storage');

CREATE TABLE PROCUREMENT (
    PO_Number VARCHAR(50) PRIMARY KEY,
    OrderDate DATETIME DEFAULT GETDATE(),
    TotalCost DECIMAL(12,2) DEFAULT 0.00,
    SupplierID VARCHAR(20) FOREIGN KEY REFERENCES SUPPLIER(SupplierID),
    AdminID VARCHAR(20) FOREIGN KEY REFERENCES [USER](UserID),
    Status VARCHAR(20) DEFAULT 'Pending' -- Pending or Completed (Goods Receipt done)
);

CREATE TABLE ITEM_MASTER (
    ItemCode VARCHAR(50) PRIMARY KEY,
    Category VARCHAR(50) FOREIGN KEY REFERENCES CATEGORY_LIST(CategoryName),
    Specs VARCHAR(255) NOT NULL,
    BaselineCost DECIMAL(10,2) NOT NULL,
    CurrentValue DECIMAL(10,2) NOT NULL,
    ItemCondition VARCHAR(20) NOT NULL, -- Brand New or Second-hand
    IsActive BIT DEFAULT 1 -- NEW: Added for Soft Deletion (Archiving)
);

CREATE TABLE STOCK_INSTANCE (
    SerialNumber VARCHAR(100) PRIMARY KEY,
    Status VARCHAR(20) DEFAULT 'Available', -- Available, Sold, Defective, Returned, Written-Off
    DefectReason VARCHAR(100) NULL, -- NEW: Added to track why item was flagged
    ItemCode VARCHAR(50) FOREIGN KEY REFERENCES ITEM_MASTER(ItemCode),
    SupplierID VARCHAR(20) FOREIGN KEY REFERENCES SUPPLIER(SupplierID),
    PO_Number VARCHAR(50) FOREIGN KEY REFERENCES PROCUREMENT(PO_Number)
);

CREATE TABLE [TRANSACTION] (
    ReceiptID VARCHAR(50) PRIMARY KEY,
    OrderDate DATETIME DEFAULT GETDATE(),
    GrandTotal DECIMAL(12,2) NOT NULL,
    CashierID VARCHAR(20) FOREIGN KEY REFERENCES [USER](UserID)
);

CREATE TABLE TRANSACTION_ITEM (
    ReceiptID VARCHAR(50) FOREIGN KEY REFERENCES [TRANSACTION](ReceiptID),
    SerialNumber VARCHAR(100) FOREIGN KEY REFERENCES STOCK_INSTANCE(SerialNumber),
    SoldPrice DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ReceiptID, SerialNumber)
);
GO

CREATE TABLE ACTIVITY_LOG (
    LogID INT IDENTITY(1,1) PRIMARY KEY,
    UserID VARCHAR(20) NOT NULL,
    ActionDescription VARCHAR(255) NOT NULL,
    LogDate DATETIME DEFAULT GETDATE()
);

-- Add Auditing Columns to ITEM_MASTER
ALTER TABLE ITEM_MASTER ADD CreatedTime DATETIME DEFAULT GETDATE();
ALTER TABLE ITEM_MASTER ADD CreatedBy VARCHAR(20) NULL FOREIGN KEY REFERENCES [USER](UserID);
ALTER TABLE ITEM_MASTER ADD LastModifiedTime DATETIME NULL;
ALTER TABLE ITEM_MASTER ADD ModifiedBy VARCHAR(20) NULL FOREIGN KEY REFERENCES [USER](UserID);
GO

-- Add the new enterprise fields to the SUPPLIER table
ALTER TABLE SUPPLIER ADD ContactPerson VARCHAR(100) NULL;
ALTER TABLE SUPPLIER ADD EmailAddress VARCHAR(100) NULL;
ALTER TABLE SUPPLIER ADD Remarks VARCHAR(255) NULL;
ALTER TABLE SUPPLIER ADD DateRegistered DATETIME DEFAULT GETDATE();
ALTER TABLE SUPPLIER ADD IsActive BIT DEFAULT 1;
GO




-- 1. GLOBAL STORE SETTINGS (Prevents hardcoding)
CREATE TABLE STORE_SETTINGS (
    StoreID INT PRIMARY KEY,
    StoreName VARCHAR(100),
    Address VARCHAR(255),
    ContactNumber VARCHAR(20),
    TIN VARCHAR(20),
    LogoPath VARCHAR(MAX)
);

-- 2. PROCUREMENT HEADER
CREATE TABLE PROCUREMENT (
    PO_Number VARCHAR(50) PRIMARY KEY,
    SupplierID VARCHAR(20) FOREIGN KEY REFERENCES SUPPLIER(SupplierID),
    OrderDate DATETIME DEFAULT GETDATE(),
    ExpectedDate DATETIME,
    Status VARCHAR(20) DEFAULT 'Draft', -- Draft, Pending Approval, Ordered, Received, Completed, Cancelled
    CreatedBy VARCHAR(20) FOREIGN KEY REFERENCES [USER](UserID),
    CreatedOn DATETIME DEFAULT GETDATE(),
    ModifiedBy VARCHAR(20) FOREIGN KEY REFERENCES [USER](UserID),
    ModifiedOn DATETIME,
    Remarks VARCHAR(MAX),
    SubTotal DECIMAL(12,2),
    Discount DECIMAL(12,2), -- Added for Zoho-style discount
    Tax DECIMAL(12,2),
    GrandTotal DECIMAL(12,2)
);

-- 3. PROCUREMENT ITEMS
CREATE TABLE PROCUREMENT_ITEM (
    ItemID INT IDENTITY(1,1) PRIMARY KEY,
    PO_Number VARCHAR(50) FOREIGN KEY REFERENCES PROCUREMENT(PO_Number),
    ItemCode VARCHAR(50) FOREIGN KEY REFERENCES ITEM_MASTER(ItemCode),
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(12,2)
);

-- 4. PROCUREMENT INVOICE (For 3-Way Matching)
CREATE TABLE PROCUREMENT_INVOICE (
    InvoiceNumber VARCHAR(50) PRIMARY KEY,
    PO_Number VARCHAR(50) FOREIGN KEY REFERENCES PROCUREMENT(PO_Number),
    InvoiceDate DATETIME,
    InvoiceAmount DECIMAL(12,2),
    InvoiceFilePath VARCHAR(MAX)
);

CREATE TABLE ATTACHMENTS (
    AttachmentID INT IDENTITY(1,1) PRIMARY KEY,
    PO_Number VARCHAR(50) NOT NULL,
    FileName NVARCHAR(255) NOT NULL,
    FilePath NVARCHAR(500) NOT NULL,
    UploadedBy NVARCHAR(100) NOT NULL,
    UploadedDate DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_Attachments_PO FOREIGN KEY (PO_Number) REFERENCES PROCUREMENT(PO_Number)
);

ALTER TABLE [TRANSACTION] ADD
    CustomerName VARCHAR(100) NULL,
    PaymentMethod VARCHAR(20) DEFAULT 'Cash',
    TransactionNumber VARCHAR(100) NULL,
    Discount DECIMAL(12,2) DEFAULT 0,
    Tax DECIMAL(12,2) DEFAULT 0,
    SubTotal DECIMAL(12,2) DEFAULT 0,
    Status VARCHAR(20) DEFAULT 'Quotation',
    WarrantyDays INT DEFAULT 7,
    CreatedBy VARCHAR(20) FOREIGN KEY REFERENCES [USER](UserID),
    CreatedOn DATETIME DEFAULT GETDATE(),
    ModifiedBy VARCHAR(20) NULL FOREIGN KEY REFERENCES [USER](UserID),
    ModifiedOn DATETIME NULL,
    Remarks VARCHAR(MAX) NULL;

ALTER TABLE ATTACHMENTS ADD TransactionID VARCHAR(50) NULL REFERENCES [TRANSACTION](ReceiptID);

-- Make PO_Number nullable so Sales attachments don't require a PO
ALTER TABLE ATTACHMENTS ALTER COLUMN PO_Number VARCHAR(50) NULL;

-- Add TransactionID column for Sales attachments
ALTER TABLE ATTACHMENTS ADD TransactionID VARCHAR(50) NULL;
ALTER TABLE ATTACHMENTS ADD CONSTRAINT FK_Attachments_Transaction FOREIGN KEY (TransactionID) REFERENCES [TRANSACTION](ReceiptID);